### PR TITLE
Updated RU Translation

### PR DESCRIPTION
**Pull request by StarterCraft**
No further information

### CODE REVIEW

**Comment by cam72cam** [comment]
@StarterCraft Can you add yourself to the Authors file?

Once you do that, this PR looks good and I will merge it.

**Comment by StarterCraft** [comment]
> @StarterCraft Can you add yourself to the Authors file?
> 
> Once you do that, this PR looks good and I will merge it.

How to do this?

**Comment by cam72cam** [comment]
Edit this file: https://github.com/StarterCraft/ImmersiveRailroading/blob/patch-1/AUTHORS

feel free to add as much or as little information as you wish

**Comment by StarterCraft** [comment]
done

**Pull request merged**
